### ISSUE TITLE
Can't enter the WebXR scene

### ISSUE THREAD

**Issue by EasonZxp** [vuer-ai/vuer#56]
## Steps to Reproduce

Input URL: https://vuer.ai/

Click Virtual Reliaty

## Hardware
Pico4 with pico's browser

I also tested with the Wolvic browser (chromium backend), also doesn't work.

**Comment by geyang** [comment]
Just to rule things out a bit, I tested Quest 3 and Vision Pro, both works.

Is this a vendor-specific issue?

**Comment by EasonZxp** [comment]
Then I test Wolvic browser （chromium backend） on Quest3， also doesn't work.
It seems to be a compatibility issue with the Chromium engine.

**Comment by Outlier-c** [comment]
When using the Quest 3's Browser, I can't even access the Vuer page. However, Wolvic can load the page, but clicking "Virtual Reality" sometimes freezes. Have you tried the Quest3's Browser? Maybe we're encountering the same issue?

**Comment by geyang** [comment]
I am using Quest3's browser, Maybe we should share the Quest OS version numbers?

I did barebone, https://vuer.ai.

**Comment by EasonZxp** [comment]
> When using the Quest 3's Browser, I can't even access the Vuer page. However, Wolvic can load the page, but clicking "Virtual Reality" sometimes freezes. Have you tried the Quest3's Browser? Maybe we're encountering the same issue?

I Test Quest3's browser, it's ok (ro.build.display.id:  **SQ3A.220605.009.A1**).

**Comment by Outlier-c** [comment]
Well, barebone is ok in Quest3's browser.(Firmware Build ID:SQ3A.220605.009.A1) My mistake, it seems that our issues are not the same problem.

**Comment by EasonZxp** [comment]
It seems that browsers using the Chromium engine all have this issue. Do you have any suggestions regarding this problem? 
I remember it worked fine before. @geyang

**Comment by shel33** [comment]
I just tested my Pico4 and can not open the vr mode as well. Should I connect some logs?

**Comment by geyang** [comment]
Yes please, logs will be very helpful. both screenshot + text.

**Comment by EasonZxp** [comment]
> Yes please, logs will be very helpful. both screenshot + text.

@geyang Hi, I captured log and video with Pico4 browser bellow:

[pico_browser.txt](https://github.com/user-attachments/files/19484613/pico_browser.txt)
https://github.com/user-attachments/assets/50a5883c-a72a-4d82-9777-acb2d1129861

**Comment by EasonZxp** [comment]
And, this is log and video with Quest3 using wolvic browser:

https://github.com/user-attachments/assets/33083451-348c-438d-8169-7f4d0df45d03
[quest3.txt](https://github.com/user-attachments/files/19484636/quest3.txt)

**Comment by geyang** [comment]
@EasonZxp you attached the video twice, so the second link is not a text file. Would you mind resend? 

Thanks for getting the log!

**Comment by EasonZxp** [comment]
> [@EasonZxp](https://github.com/EasonZxp) you attached the video twice, so the second link is not a text file. Would you mind resend?
> 
> Thanks for getting the log!

I think you might have misread? I uploaded the videos and logs for Quest 3 and Pico 4 separately. There are 4 links above.
pico_browser.txt and quest3.txt are the log files

**Comment by geyang** [comment]
got it!

**Comment by geyang** [comment]
I took a look, those are system logs. It will be more helpful if we take a look at the browser console logs. Search for "getting browser console logs from pico VR"

**Comment by EasonZxp** [comment]
> I took a look, those are system logs. It will be more helpful if we take a look at the browser console logs. Search for "getting browser console logs from pico VR"

Got it. If we need to capture browser-side logs, I can try grabbing Quest's first tomorrow—I only have a Quest device on hand right now.

**Comment by EasonZxp** [comment]
@geyang Hi, I captured the console log on Q3 with wolvic browser, please help to check:

[q3_wolvic_chriomium_browser_console_log.txt](https://github.com/user-attachments/files/19524021/q3_wolvic_chriomium_browser_console_log.txt)

**Comment by geyang** [comment]
@EasonZxp I am looking at the log. Are there specific features you need from this browser?

We need to rule out that the possibility that webXR is not well supported by this browser. You can test by visiting this example: https://immersiveweb.dev/

and these
- https://immersive-web.github.io/webxr-samples/

**Comment by EasonZxp** [comment]
@geyang yes, https://immersiveweb.dev/ and https://immersive-web.github.io/webxr-samples/  samples can enter webxr scene

**Comment by shel33** [comment]
I saw the below info from the log: store.js:324 Feature 'dom-overlay' is not supported for mode: immersive-v
Does the https://vuer.ai/ use the dom overlay feature?

**Comment by EasonZxp** [comment]
@geyang Hi geyang, 

I noticed Chromium’s code explicitly restricts DOM Overlay in immersive VR mode here:

https://github.com/chromium/chromium/blob/main/third_party/blink/renderer/modules/xr/xr_system.cc#L187

This could explain the compatibility gap.

Btw, have you recently upgraded the @pmndrs/xr library? Maybe issue occurred with the version upgrade? Of course, this is just my hypothesis.

Thanks.

**Comment by Yanbing-Han** [comment]
Thanks for reporting the issue!

In the latest version of **Vuer**, this problem has been resolved. We tested the following combinations and confirmed that entering the WebXR scene works correctly:

- **Device**: PICO4  **Browser**: PICO4’s built-in browser  
- **Device**: PICO4  **Browser**: Wolvic  
- **Device**: Quest 3  **Browser**: Quest 3’s built-in browser  
- **Device**: Quest 3  **Browser**: Wolvic  

Let us know if you're still experiencing any issues!

**Comment by EasonZxp** [comment]
> Thanks for reporting the issue!
> 
> In the latest version of **Vuer**, this problem has been resolved. We tested the following combinations and confirmed that entering the WebXR scene works correctly:
> 
> * **Device**: PICO4  **Browser**: PICO4’s built-in browser
> * **Device**: PICO4  **Browser**: Wolvic
> * **Device**: Quest 3  **Browser**: Quest 3’s built-in browser
> * **Device**: Quest 3  **Browser**: Wolvic
> 
> Let us know if you're still experiencing any issues!

Hi Yanbing:

Emmm.

I tested the wolvic-chromium backend browser on Quest3 with the url https://vuer.ai , the issue still there. 

The apk i used:
([Wolvic-oculusvr-arm64-chromium-generic-release.apk](https://github.com/Igalia/wolvic/releases/download/v1.2.2-chromium/Wolvic-oculusvr-arm64-chromium-generic-release.apk))

**Comment by Yanbing-Han** [comment]
Hi, sorry for the late reply.

Could you please try the latest version of Wolvic?
https://github.com/Igalia/wolvic/releases/download/v1.8.2/Wolvic-oculusvr-arm64-gecko-generic-release.apk

I just tested it again, and this version works for me.

**Comment by EasonZxp** [comment]
> Hi, sorry for the late reply.
> 
> Could you please try the latest version of Wolvic? https://github.com/Igalia/wolvic/releases/download/v1.8.2/Wolvic-oculusvr-arm64-gecko-generic-release.apk
> 
> I just tested it again, and this version works for me.

wolvic based gecko backend has no this issue. 

This issue is occurred on wolvic chromium backend.
